title: Its Pelle 
logo: docs/assets/Youtube Logo.jpg
description: ItsPelle is a Kenyan Artist who excels in different genres and worth your listen. In 2025 Apelles Kamau stepped into a studio went on to drop his ever first song in his Music Career.
#show_downloads: true
theme: jekyll-theme-minimal
